apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "vault.fullname" . }}"
  labels:
    app: "{{ template "vault.name" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  server.crt: {{ .Values.tls.crt | quote }}
  server.key: {{ .Values.tls.key | quote }}
